name = "Wilding Theme"

[author]
  name = "Michael WC Wilding"
  homepage = "http://github.com/umamiMike/wilding-theme"

# If porting an existing theme
[original]
  name = "Thomas Park"
  homepage = "http://bootswatch.com"
  repo = "https://github.com/thomaspark/bootswatch"
homepage = "https://github.com/nilproductions/hugo-bootswatch"

license = "MIT"
licenselink = "https://github.com/umamiMike/wilding-theme/LICENSE.md"
description = "Bootswatch Theme (Bootstrap 3) for Hugo"
tags = ["resume", "blog"]
features = []
min_version= 0.1
